
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 6;
  public static final int LETRA = 17;
  public static final int COMILLAS = 15;
  public static final int BARRAS = 3;
  public static final int LLAVECIERRA = 12;
  public static final int COMA = 5;
  public static final int PARENTESISABRE = 9;
  public static final int EOF = 0;
  public static final int DEF = 2;
  public static final int PIE = 4;
  public static final int error = 1;
  public static final int CORCHETEABRE = 13;
  public static final int PUNTOCOMA = 7;
  public static final int ENTERO = 16;
  public static final int PARENTESISCIERRA = 10;
  public static final int CORCHETECIERRA = 14;
  public static final int MAS = 8;
  public static final int LLAVEABRE = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DEF",
  "BARRAS",
  "PIE",
  "COMA",
  "DOSPUNTOS",
  "PUNTOCOMA",
  "MAS",
  "PARENTESISABRE",
  "PARENTESISCIERRA",
  "LLAVEABRE",
  "LLAVECIERRA",
  "CORCHETEABRE",
  "CORCHETECIERRA",
  "COMILLAS",
  "ENTERO",
  "LETRA"
  };
}

